// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ProjectApp.Core.Models;

public partial class ATSContext : DbContext
{
    public ATSContext(DbContextOptions<ATSContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Tbl_Department> Tbl_Departments { get; set; }

    public virtual DbSet<Tbl_Role> Tbl_Roles { get; set; }

    public virtual DbSet<Tbl_Section> Tbl_Sections { get; set; }

    public virtual DbSet<Tbl_User> Tbl_Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Tbl_Department>(entity =>
        {
            entity.ToTable("Tbl_Department");

            entity.Property(e => e.DepartmentName).IsRequired();
        });

        modelBuilder.Entity<Tbl_Role>(entity =>
        {
            entity.ToTable("Tbl_Role");

            entity.Property(e => e.RoleDescription).IsRequired();
            entity.Property(e => e.RoleName).IsRequired();
        });

        modelBuilder.Entity<Tbl_Section>(entity =>
        {
            entity.ToTable("Tbl_Section");

            entity.HasIndex(e => e.DepartmentId, "IX_Tbl_Section_DepartmentId");

            entity.HasIndex(e => e.EntryUserId, "IX_Tbl_Section_EntryUserId");

            entity.HasIndex(e => e.UpdateUserId, "IX_Tbl_Section_UpdateUserId");

            entity.Property(e => e.SectionName).IsRequired();
            entity.Property(e => e.ShortCode).IsRequired();

            entity.HasOne(d => d.Department).WithMany(p => p.Tbl_Sections).HasForeignKey(d => d.DepartmentId);

            entity.HasOne(d => d.EntryUser).WithMany(p => p.Tbl_SectionEntryUsers).HasForeignKey(d => d.EntryUserId);

            entity.HasOne(d => d.UpdateUser).WithMany(p => p.Tbl_SectionUpdateUsers).HasForeignKey(d => d.UpdateUserId);
        });

        modelBuilder.Entity<Tbl_User>(entity =>
        {
            entity.HasIndex(e => e.RoleId, "IX_Tbl_Users_RoleId");

            entity.Property(e => e.BloodGroup).IsRequired();
            entity.Property(e => e.Email).IsRequired();
            entity.Property(e => e.Gender).IsRequired();
            entity.Property(e => e.Password).IsRequired();
            entity.Property(e => e.PhoneNumber).IsRequired();
            entity.Property(e => e.UserName).IsRequired();

            entity.HasOne(d => d.Role).WithMany(p => p.Tbl_Users).HasForeignKey(d => d.RoleId);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}