// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectApp.Core.Models;

public partial class CB_AbsorptionEntry
{
    public int EntryId { get; set; }

    public int ProjectId { get; set; }

    public int TreeId { get; set; }

    public int TreeCount { get; set; }

    public double Co2Total { get; set; }

    public bool? IsActive { get; set; }

    public int? EntryBy { get; set; }

    public DateTime? EntryDate { get; set; }

    public int? UpdateBy { get; set; }

    public DateTime? UpdateDate { get; set; }

    public virtual CB_PlantationProject Project { get; set; }

    public virtual CB_MasterTree Tree { get; set; }
}