// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectApp.Core.Models;

public partial class CB_Department
{
    public int DepartmentId { get; set; }

    public string DepartmentName { get; set; }

    public bool? IsActive { get; set; }

    public int? EntryBy { get; set; }

    public int? UpdateBy { get; set; }

    public DateTime? EntryDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual ICollection<CB_User> CB_Users { get; set; } = new List<CB_User>();
}