// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectApp.Core.Models;

public partial class CB_EmissionFactor
{
    public int EmissionFactorId { get; set; }

    public decimal CO2_Factor_KgPerL { get; set; }

    public bool? IsActive { get; set; }

    public int? EntryBy { get; set; }

    public DateTime? EntryDate { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? UpdateDate { get; set; }

    public int? FuelId { get; set; }

    public decimal? NO2_Factor_KgPerL { get; set; }

    public decimal? CH4_Factor_KgPerL { get; set; }

    public virtual ICollection<CB_GeneratorOperation> CB_GeneratorOperations { get; set; } = new List<CB_GeneratorOperation>();

    public virtual ICollection<CB_VehicleTripEmission> CB_VehicleTripEmissions { get; set; } = new List<CB_VehicleTripEmission>();

    public virtual CB_MasterFuelType Fuel { get; set; }
}