// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectApp.Core.Models;

public partial class CB_FinalEntry
{
    public int FinalEntryId { get; set; }

    public int? ProjectId { get; set; }

    public decimal? TotalActualCo2 { get; set; }

    public int? TotalActualTrees { get; set; }

    public bool? IsActive { get; set; }

    public int? EntryBy { get; set; }

    public DateTime? EntryDate { get; set; }

    public int? UpdateBy { get; set; }

    public DateTime? UpdateDate { get; set; }

    public virtual ICollection<CB_FinalEntryDetail> CB_FinalEntryDetails { get; set; } = new List<CB_FinalEntryDetail>();
}