// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectApp.Core.Models;

public partial class CB_GeneratorOperation
{
    public int OperationId { get; set; }

    public int GeneratorId { get; set; }

    public DateOnly OperationDate { get; set; }

    public TimeOnly StartTime { get; set; }

    public TimeOnly EndTime { get; set; }

    public decimal? RunHours { get; set; }

    public decimal? LoadFactor { get; set; }

    public decimal? PowerOutputKWH { get; set; }

    public decimal? FuelConsumedLiters { get; set; }

    public int FuelId { get; set; }

    public int EntryBy { get; set; }

    public DateTime EntryDate { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? UpdateDate { get; set; }

    public bool IsDeleted { get; set; }

    public virtual CB_MasterFuelType Fuel { get; set; }

    public virtual CB_MasterGenerator Generator { get; set; }
}