// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectApp.Core.Models;

public partial class CB_GeneratorOperation
{
    public int OperationId { get; set; }

    public int GeneratorId { get; set; }

    public DateOnly OperationDate { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public decimal? RunHours { get; set; }

    public decimal? LoadFactor { get; set; }

    public decimal? PowerOutputKWH { get; set; }

    public decimal? FuelConsumedLiters { get; set; }

    public int EntryBy { get; set; }

    public DateTime EntryDate { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? UpdateDate { get; set; }

    public bool IsDeleted { get; set; }

    public decimal? co2_kg { get; set; }

    public decimal? no2_kg { get; set; }

    public decimal? ch4_kg { get; set; }

    public decimal? total_co2_kg { get; set; }

    public decimal? total_no2_kg { get; set; }

    public decimal? total_ch4_kg { get; set; }

    public decimal? total_co2e_kg { get; set; }

    public int StatusId { get; set; }

    public int? SiteId { get; set; }

    public virtual CB_MasterGenerator Generator { get; set; }

    public virtual CB_MasterSiteLocation Site { get; set; }
}