// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectApp.Core.Models;

public partial class CB_GeneratorOperationHistory
{
    public int HistoryId { get; set; }

    public int OperationId { get; set; }

    public int ActionId { get; set; }

    public int ActionBy { get; set; }

    public DateTime ActionDate { get; set; }

    public int StatusId { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public int EntryBy { get; set; }

    public DateTime EntryDate { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }
}