// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectApp.Core.Models;

public partial class CB_MasterGenerator
{
    public int GeneratorId { get; set; }

    public string GeneratorName { get; set; }

    public int FuelId { get; set; }

    public decimal RatedCapacityKW { get; set; }

    public int SiteId { get; set; }

    public int DepartmentId { get; set; }

    public bool IsActive { get; set; }

    public int EntryBy { get; set; }

    public DateTime EntryDate { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? UpdateDate { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<CB_GeneratorOperation> CB_GeneratorOperations { get; set; } = new List<CB_GeneratorOperation>();

    public virtual CB_Department Department { get; set; }

    public virtual CB_MasterFuelType Fuel { get; set; }

    public virtual CB_MasterSiteLocation Site { get; set; }
}