// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectApp.Core.Models;

public partial class CB_Master_Vehicle_Type
{
    public int vehicle_type_id { get; set; }

    public string vehicle_type_name { get; set; }

    public string vehicle_category { get; set; }

    public int? fuel_id { get; set; }

    public decimal? average_mileage_kmpl { get; set; }

    public string description { get; set; }

    public bool IsActive { get; set; }

    public int EntryBy { get; set; }

    public DateTime EntryDate { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? UpdateDate { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<CB_Master_Vehicle> CB_Master_Vehicles { get; set; } = new List<CB_Master_Vehicle>();

    public virtual CB_Master_Fuel fuel { get; set; }
}