// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectApp.Core.Models;

public partial class CB_MasterWorkflow
{
    public int WorkflowId { get; set; }

    public int? CurrentStatusId { get; set; }

    public int ActionId { get; set; }

    public int NextStatusId { get; set; }

    public int RoleId { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual CB_MasterAction Action { get; set; }

    public virtual CB_MasterStatus CurrentStatus { get; set; }

    public virtual CB_MasterStatus NextStatus { get; set; }

    public virtual CB_Role Role { get; set; }
}