// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectApp.Core.Models;

public partial class CB_MasterSiteLocation
{
    public int SiteId { get; set; }

    public string SiteName { get; set; }

    public string BuildingName { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public bool IsActive { get; set; }

    public int EntryBy { get; set; }

    public DateTime EntryDate { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? UpdateDate { get; set; }

    public bool IsDeleted { get; set; }

    public string ShortCode { get; set; }

    public virtual ICollection<CB_GeneratorOperation> CB_GeneratorOperations { get; set; } = new List<CB_GeneratorOperation>();

    public virtual ICollection<CB_MasterGenerator> CB_MasterGenerators { get; set; } = new List<CB_MasterGenerator>();
}