// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectApp.Core.Models;

public partial class CB_MasterCity
{
    public int CityId { get; set; }

    public string CityName { get; set; }

    public string StateName { get; set; }

    public string Pincode { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public int EntryBy { get; set; }

    public DateTime EntryDate { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? UpdateDate { get; set; }

    public virtual ICollection<CB_VehicleTrip> CB_VehicleTripFromCities { get; set; } = new List<CB_VehicleTrip>();

    public virtual ICollection<CB_VehicleTrip> CB_VehicleTripToCities { get; set; } = new List<CB_VehicleTrip>();
}