// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectApp.Core.Models;

public partial class CB_MasterNGO
{
    public int NgoId { get; set; }

    public string NgoName { get; set; }

    public string ContactPerson { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Location { get; set; }

    public bool? IsActive { get; set; }

    public int? EntryBy { get; set; }

    public DateTime? EntryDate { get; set; }

    public int? UpdateBy { get; set; }

    public DateTime? UpdateDate { get; set; }

    public virtual ICollection<CB_PlantationProject> CB_PlantationProjects { get; set; } = new List<CB_PlantationProject>();
}