// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectApp.Core.Models;

public partial class CB_Master_Fuel
{
    public int fuel_id { get; set; }

    public string fuel_name { get; set; }

    public decimal co2_factor { get; set; }

    public decimal nox_factor { get; set; }

    public decimal ch4_factor { get; set; }

    public bool IsActive { get; set; }

    public int? EntryBy { get; set; }

    public DateTime EntryDate { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? UpdateDate { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<CB_Master_Vehicle_Type> CB_Master_Vehicle_Types { get; set; } = new List<CB_Master_Vehicle_Type>();

    public virtual ICollection<CB_Master_Vehicle> CB_Master_Vehicles { get; set; } = new List<CB_Master_Vehicle>();
}