// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectApp.Core.Models;

public partial class CB_MasterStatus
{
    public int Statusid { get; set; }

    public string Status { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<CB_GeneratorOperation> CB_GeneratorOperations { get; set; } = new List<CB_GeneratorOperation>();

    public virtual ICollection<CB_VehicleTripEmission> CB_VehicleTripEmissions { get; set; } = new List<CB_VehicleTripEmission>();
}