// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectApp.Core.Models;

public partial class CB_MasterVehicleType
{
    public int vehicle_type_id { get; set; }

    public string vehicle_type_name { get; set; }

    public string description { get; set; }

    public bool IsActive { get; set; }

    public int EntryBy { get; set; }

    public DateTime EntryDate { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? UpdateDate { get; set; }

    public bool IsDeleted { get; set; }

    public int? CategoryId { get; set; }

    public virtual ICollection<CB_MasterVehicle> CB_MasterVehicles { get; set; } = new List<CB_MasterVehicle>();

    public virtual CB_VehicleTypeCategory Category { get; set; }
}