// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectApp.Core.Models;

public partial class CB_MasterFuelType
{
    public int fuel_id { get; set; }

    public string fuel_name { get; set; }

    public bool IsActive { get; set; }

    public int? EntryBy { get; set; }

    public DateTime EntryDate { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? UpdateDate { get; set; }

    public bool IsDeleted { get; set; }

    public bool isapplicable { get; set; }

    public string fuel_Desc { get; set; }

    public virtual ICollection<CB_EmissionFactor> CB_EmissionFactors { get; set; } = new List<CB_EmissionFactor>();

    public virtual ICollection<CB_MasterGenerator> CB_MasterGenerators { get; set; } = new List<CB_MasterGenerator>();

    public virtual ICollection<CB_MasterVehicle> CB_MasterVehicles { get; set; } = new List<CB_MasterVehicle>();
}