// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectApp.Core.Models;

public partial class CB_MasterAction
{
    public int ActionId { get; set; }

    public string ActionName { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual ICollection<CB_MasterWorkflow> CB_MasterWorkflows { get; set; } = new List<CB_MasterWorkflow>();
}