// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectApp.Core.Models;

public partial class CB_MasterTree
{
    public int TreeId { get; set; }

    public string TreeName { get; set; }

    public decimal co2AbsorptionPerYear { get; set; }

    public bool? IsActive { get; set; }

    public int? EntryBy { get; set; }

    public DateTime? EntryDate { get; set; }

    public int? UpdateBy { get; set; }

    public DateTime? UpdateDate { get; set; }

    public decimal? co2AbsorptionPerMonth { get; set; }

    public decimal? co2AbsorptionPerDaily { get; set; }

    public virtual ICollection<CB_AbsorptionEntry> CB_AbsorptionEntries { get; set; } = new List<CB_AbsorptionEntry>();

    public virtual ICollection<CB_OffsetEntryDetail> CB_OffsetEntryDetails { get; set; } = new List<CB_OffsetEntryDetail>();
}