// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectApp.Core.Models;

public partial class CB_Master_Vehicle
{
    public int vehicle_id { get; set; }

    public string vehicle_number { get; set; }

    public int vehicle_type_id { get; set; }

    public int fuel_id { get; set; }

    public int department_id { get; set; }

    public int? engine_capacity { get; set; }

    public string emission_standard { get; set; }

    public bool IsActive { get; set; }

    public int? EntryBy { get; set; }

    public DateTime EntryDate { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? UpdateDate { get; set; }

    public bool IsDeleted { get; set; }

    public virtual CB_Department department { get; set; }

    public virtual CB_Master_Fuel fuel { get; set; }

    public virtual CB_Master_Vehicle_Type vehicle_type { get; set; }
}