// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectApp.Core.Models;

public partial class CB_OffsetEntryDetail
{
    public int Id { get; set; }

    public int OffsetEntryId { get; set; }

    public int TreeId { get; set; }

    public int TreeCount { get; set; }

    public decimal? Co2Total { get; set; }

    public bool? IsActive { get; set; }

    public string EntryBy { get; set; }

    public DateTime? EntryDate { get; set; }

    public string UpdateBy { get; set; }

    public DateTime? UpdateDate { get; set; }

    public virtual CB_OffsetEntry OffsetEntry { get; set; }

    public virtual CB_MasterTree Tree { get; set; }
}