// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectApp.Core.Models;

public partial class CB_OffsetEntry
{
    public int OffsetEntryId { get; set; }

    public int ProjectId { get; set; }

    public decimal? PreviousYearEmission { get; set; }

    public decimal? TotalOffset { get; set; }

    public bool? IsActive { get; set; }

    public string EntryBy { get; set; }

    public DateTime? EntryDate { get; set; }

    public string UpdateBy { get; set; }

    public DateTime? UpdateDate { get; set; }

    public bool? IsDraft { get; set; }

    public virtual ICollection<CB_OffsetEntryDetail> CB_OffsetEntryDetails { get; set; } = new List<CB_OffsetEntryDetail>();

    public virtual CB_PlantationProject Project { get; set; }
}