// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectApp.Core.Models;

public partial class CB_PlantationProject
{
    public int ProjectId { get; set; }

    public int NgoId { get; set; }

    public string ProjectName { get; set; }

    public string Address { get; set; }

    public int? CityId { get; set; }

    public bool? IsActive { get; set; }

    public int? EntryBy { get; set; }

    public DateTime? EntryDate { get; set; }

    public int? UpdateBy { get; set; }

    public DateTime? UpdateDate { get; set; }

    public virtual ICollection<CB_TreePlantationEntry> CB_TreePlantationEntries { get; set; } = new List<CB_TreePlantationEntry>();

    public virtual CB_MasterCity City { get; set; }

    public virtual CB_MasterNGO Ngo { get; set; }
}