// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectApp.Core.Models;

public partial class CB_User
{
    public int UserId { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public int? RoleId { get; set; }

    public int? DepartmentId { get; set; }

    public bool? IsActive { get; set; }

    public int? EntryBy { get; set; }

    public int? UpdateBy { get; set; }

    public DateTime? EntryDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public virtual ICollection<CB_UserRoleMapping> CB_UserRoleMappings { get; set; } = new List<CB_UserRoleMapping>();

    public virtual CB_Department Department { get; set; }

    public virtual CB_Role Role { get; set; }
}