// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectApp.Core.Models;

public partial class CB_UserRoleMapping
{
    public int id { get; set; }

    public int? UserId { get; set; }

    public int? RoleId { get; set; }

    public bool? IsActive { get; set; }

    public virtual CB_Role Role { get; set; }

    public virtual CB_User User { get; set; }
}