// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectApp.Core.Models;

public partial class CB_User
{
    public int UserId { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public int? DepartmentId { get; set; }

    public bool? IsActive { get; set; }

    public int? EntryBy { get; set; }

    public int? UpdateBy { get; set; }

    public DateTime? EntryDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public bool? IsDeleted { get; set; }

    public string Fname { get; set; }

    public string Lname { get; set; }

    public string UserName { get; set; }

    public virtual ICollection<CB_UserRoleMapping> CB_UserRoleMappings { get; set; } = new List<CB_UserRoleMapping>();

    public virtual ICollection<CB_VehicleTrip> CB_VehicleTripEntryByNavigations { get; set; } = new List<CB_VehicleTrip>();

    public virtual ICollection<CB_VehicleTrip> CB_VehicleTripUpdatedByNavigations { get; set; } = new List<CB_VehicleTrip>();

    public virtual CB_Department Department { get; set; }
}