// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectApp.Core.Models;

public partial class CB_VehicleTripEmission
{
    public int tripid { get; set; }

    public int vehicleid { get; set; }

    public int fromcityid { get; set; }

    public int tocityid { get; set; }

    public DateTime tripstartdatetime { get; set; }

    public DateTime? tripenddatetime { get; set; }

    public decimal distancekm { get; set; }

    public string fueltype { get; set; }

    public decimal fuelconsumedltr { get; set; }

    public decimal? totalco2 { get; set; }

    public decimal? totalno2 { get; set; }

    public decimal? totalch4 { get; set; }

    public decimal? totalemission { get; set; }

    public bool isactive { get; set; }

    public int entryby { get; set; }

    public DateTime entrydate { get; set; }

    public int? updateby { get; set; }

    public DateTime? updatedate { get; set; }

    public int StatusId { get; set; }

    public decimal? co2 { get; set; }

    public decimal? no2 { get; set; }

    public decimal? ch4 { get; set; }

    public string reportId { get; set; }

    public bool IsFlag { get; set; }

    public virtual CB_MasterStatus Status { get; set; }

    public virtual CB_User entrybyNavigation { get; set; }

    public virtual CB_MasterCity fromcity { get; set; }

    public virtual CB_MasterCity tocity { get; set; }

    public virtual CB_User updatebyNavigation { get; set; }

    public virtual CB_MasterVehicle vehicle { get; set; }
}