// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectApp.Core.Models;

public partial class CB_VehicleTrip
{
    public int TripId { get; set; }

    public int VehicleId { get; set; }

    public int FromCityId { get; set; }

    public int ToCityId { get; set; }

    public DateTime TripStartDateTime { get; set; }

    public DateTime? TripEndDateTime { get; set; }

    public decimal DistanceKm { get; set; }

    public decimal FuelConsumedLtr { get; set; }

    public string TripStatus { get; set; }

    public int EntryBy { get; set; }

    public DateTime EntryDate { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? UpdateDate { get; set; }

    public bool IsDeleted { get; set; }

    public virtual CB_User EntryByNavigation { get; set; }

    public virtual CB_MasterCity FromCity { get; set; }

    public virtual CB_MasterCity ToCity { get; set; }

    public virtual CB_User UpdatedByNavigation { get; set; }

    public virtual CB_MasterVehicle Vehicle { get; set; }
}