// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectApp.Core.Models;

public partial class CB_VehicleTypeCategory
{
    public int Id { get; set; }

    public string Category { get; set; }

    public bool IsActive { get; set; }

    public int EntryBy { get; set; }

    public DateTime EntryDate { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? UpdateDate { get; set; }

    public virtual ICollection<CB_MasterVehicleType> CB_MasterVehicleTypes { get; set; } = new List<CB_MasterVehicleType>();
}