// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectApp.Core.Models;

public partial class CB_Workflow
{
    public int workflowId { get; set; }

    public int? currentstatusId { get; set; }

    public int? nextstatusId { get; set; }

    public bool? isactive { get; set; }

    public bool? isdeleted { get; set; }

    public int? ActionId { get; set; }

    public int? RoleId { get; set; }

    public virtual CB_Action Action { get; set; }

    public virtual CB_Role Role { get; set; }
}