// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ProjectApp.Core.Models;

public partial class CBContext : DbContext
{
    public CBContext(DbContextOptions<CBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CB_Department> CB_Departments { get; set; }

    public virtual DbSet<CB_Master_City> CB_Master_Cities { get; set; }

    public virtual DbSet<CB_Master_Fuel> CB_Master_Fuels { get; set; }

    public virtual DbSet<CB_Master_Vehicle> CB_Master_Vehicles { get; set; }

    public virtual DbSet<CB_Master_Vehicle_Type> CB_Master_Vehicle_Types { get; set; }

    public virtual DbSet<CB_Role> CB_Roles { get; set; }

    public virtual DbSet<CB_User> CB_Users { get; set; }

    public virtual DbSet<CB_UserRoleMapping> CB_UserRoleMappings { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CB_Department>(entity =>
        {
            entity.HasKey(e => e.DepartmentId).HasName("PK__CB_Depar__B2079BED8E6AD1B5");

            entity.ToTable("CB_Department");

            entity.Property(e => e.DepartmentName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.EntryDate).HasColumnType("datetime");
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<CB_Master_City>(entity =>
        {
            entity.HasKey(e => e.CityId).HasName("PK__CB_Maste__F2D21B76AD4B5974");

            entity.ToTable("CB_Master_City");

            entity.Property(e => e.CityName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.EntryDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Pincode)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.StateName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<CB_Master_Fuel>(entity =>
        {
            entity.HasKey(e => e.fuel_id).HasName("PK__CB_Maste__A40C1884DD9ACC8E");

            entity.ToTable("CB_Master_Fuel");

            entity.Property(e => e.EntryDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");
            entity.Property(e => e.ch4_factor).HasColumnType("decimal(16, 8)");
            entity.Property(e => e.co2_factor).HasColumnType("decimal(16, 8)");
            entity.Property(e => e.fuel_name)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.nox_factor).HasColumnType("decimal(16, 8)");
        });

        modelBuilder.Entity<CB_Master_Vehicle>(entity =>
        {
            entity.HasKey(e => e.vehicle_id).HasName("PK__CB_Maste__F2947BC1DBB88EBF");

            entity.ToTable("CB_Master_Vehicle");

            entity.HasIndex(e => e.vehicle_number, "UQ_vehicle_number").IsUnique();

            entity.Property(e => e.EntryDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");
            entity.Property(e => e.emission_standard)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.vehicle_number)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.department).WithMany(p => p.CB_Master_Vehicles)
                .HasForeignKey(d => d.department_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Vehicle_Department");

            entity.HasOne(d => d.fuel).WithMany(p => p.CB_Master_Vehicles)
                .HasForeignKey(d => d.fuel_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Vehicle_Fuel");

            entity.HasOne(d => d.vehicle_type).WithMany(p => p.CB_Master_Vehicles)
                .HasForeignKey(d => d.vehicle_type_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Vehicle_VehicleType");
        });

        modelBuilder.Entity<CB_Master_Vehicle_Type>(entity =>
        {
            entity.HasKey(e => e.vehicle_type_id).HasName("PK__CB_Maste__2A00721841B4422D");

            entity.ToTable("CB_Master_Vehicle_Type");

            entity.Property(e => e.EntryDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");
            entity.Property(e => e.average_mileage_kmpl).HasColumnType("decimal(6, 2)");
            entity.Property(e => e.description)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.vehicle_category)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.vehicle_type_name)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);

            entity.HasOne(d => d.fuel).WithMany(p => p.CB_Master_Vehicle_Types)
                .HasForeignKey(d => d.fuel_id)
                .HasConstraintName("FK_vehicleType_fuel");
        });

        modelBuilder.Entity<CB_Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__CB_Role__8AFACE1A4E6560C1");

            entity.ToTable("CB_Role");

            entity.Property(e => e.Description)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.EntryDate).HasColumnType("datetime");
            entity.Property(e => e.RoleName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<CB_User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__CB_User__1788CC4C129F2098");

            entity.ToTable("CB_User");

            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.EntryDate).HasColumnType("datetime");
            entity.Property(e => e.Fname)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.Lname)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasDefaultValue("");
            entity.Property(e => e.Password)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasDefaultValue("");

            entity.HasOne(d => d.Department).WithMany(p => p.CB_Users)
                .HasForeignKey(d => d.DepartmentId)
                .HasConstraintName("FK_CBUser_Department");
        });

        modelBuilder.Entity<CB_UserRoleMapping>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__CB_UserR__3213E83F76D89AD1");

            entity.ToTable("CB_UserRoleMapping");

            entity.HasOne(d => d.Role).WithMany(p => p.CB_UserRoleMappings)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("FK_UserRoleMapping_Roles");

            entity.HasOne(d => d.User).WithMany(p => p.CB_UserRoleMappings)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_UserRoleMapping_Users");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}