

// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ProjectApp.Core.Models;

public partial class CBContext : DbContext
{
    public CBContext(DbContextOptions<CBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CB_Department> CB_Departments { get; set; }

    public virtual DbSet<CB_Role> CB_Roles { get; set; }

    public virtual DbSet<CB_User> CB_Users { get; set; }

    public virtual DbSet<CB_UserRoleMapping> CB_UserRoleMappings { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CB_Department>(entity =>
        {
            entity.HasKey(e => e.DepartmentId);

            entity.Property(e => e.DepartmentId).ValueGeneratedNever();
            entity.Property(e => e.DepartmentName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.EntryDate).HasColumnType("datetime");
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<CB_Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__CB_Roles__8AFACE1A9AA4651F");

            entity.Property(e => e.RoleId).ValueGeneratedNever();
            entity.Property(e => e.Description)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.EntryDate).HasColumnType("datetime");
            entity.Property(e => e.RoleName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<CB_User>(entity =>
        {
            entity.HasKey(e => e.UserId);

            entity.ToTable("CB_User");

            entity.Property(e => e.UserId).ValueGeneratedNever();
            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.EntryDate).HasColumnType("datetime");
            entity.Property(e => e.FullName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Password)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");

            entity.HasOne(d => d.Department).WithMany(p => p.CB_Users)
                .HasForeignKey(d => d.DepartmentId)
                .HasConstraintName("FK_Users_Department");

        });

        modelBuilder.Entity<CB_UserRoleMapping>(entity =>
        {
            entity.ToTable("CB_UserRoleMapping");

            entity.Property(e => e.id).ValueGeneratedNever();

            entity.HasOne(d => d.Role).WithMany(p => p.CB_UserRoleMappings)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("FK_Roles_UserRoleMapping");

            entity.HasOne(d => d.User).WithMany(p => p.CB_UserRoleMappings)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_Users_UserRoleMapping");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}