// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectApp.Core.Models;

public partial class Tbl_User
{
    public int Id { get; set; }

    public string UserName { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public DateOnly DateOfBirth { get; set; }

    public string Gender { get; set; }

    public string PhoneNumber { get; set; }

    public string BloodGroup { get; set; }

    public int RoleId { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Tbl_Role Role { get; set; }

    public virtual ICollection<Tbl_Section> Tbl_SectionEntryUsers { get; set; } = new List<Tbl_Section>();

    public virtual ICollection<Tbl_Section> Tbl_SectionUpdateUsers { get; set; } = new List<Tbl_Section>();
}