// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectApp.Core.Models;

public partial class Tbl_Department
{
    public int id { get; set; }

    public string DepartmentName { get; set; }

    public virtual ICollection<Tbl_Section> Tbl_Sections { get; set; } = new List<Tbl_Section>();
}