// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectApp.Core.Models;

public partial class Tbl_Section
{
    public int id { get; set; }

    public string SectionName { get; set; }

    public string ShortCode { get; set; }

    public int DepartmentId { get; set; }

    public bool IsActive { get; set; }

    public DateTime EntryDate { get; set; }

    public int EntryBy { get; set; }

    public DateTime UpdateDate { get; set; }

    public int? UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public int? EntryUserId { get; set; }

    public int? UpdateUserId { get; set; }

    public virtual Tbl_Department Department { get; set; }

    public virtual Tbl_User EntryUser { get; set; }

    public virtual Tbl_User UpdateUser { get; set; }
}