// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectApp.Core.Models;

public partial class Tbl_Role
{
    public int Id { get; set; }

    public string RoleName { get; set; }

    public string RoleDescription { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<Tbl_User> Tbl_Users { get; set; } = new List<Tbl_User>();
}